feat: mock fix

diff --git a/.github/workflows/apidocs-upload.yml b/.github/workflows/apidocs-upload.yml
--- a/.github/workflows/apidocs-upload.yml
+++ b/.github/workflows/apidocs-upload.yml
@@ -22,19 +22,23 @@ jobs:
             version="${GITHUB_REF#refs/tags/}"
             echo "version=$version"
 
-            # Pattern that accepts "v1.0.0" , "v2.4.6". 
+            # Pattern that accepts releases: "v1.0.0" , "v2.4.6". 
             if [[ "$version" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
               result=isRelease
-            # Pattern that accepts "v1.0.0-rc1".
-            elif [[ "$version" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+$ ]]; then
+            # Pattern that accepts release candidates: "v1.0.0-rc.1".
+            elif [[ "$version" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$ ]]; then
               result=isReleaseCandidate
+            # Pattern that accepts "v1.0.0-rc1", an invalid rc notation.
+            elif [[ "$version" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+$ ]]; then
+              echo "release candidate version is invalid"
+              exit 1
             else
               result=isNotRelease
             fi
           else
             result=isNotTag
           fi
-  
+          
           echo $result
           echo "version_status_output=$result" >> $GITHUB_OUTPUT
 
@@ -67,4 +71,4 @@ jobs:
           node-version: ${{ matrix.node-version }}
       - name: Install dependencies (mock)
         run: echo "Mock running with ${{ env.release_status }}"
-      
+
